from pathlib import Path

ROOT = Path(__file__).resolve().parent
RAW_DIR = ROOT / "raw"
RESULTS_DIR = ROOT / "results"
CACHE_DIR = ROOT / "cache"
for _d in (RAW_DIR, RESULTS_DIR, CACHE_DIR):
    _d.mkdir(exist_ok=True)

SEED = 51
HORIZON = 4
QUANTILE_LEVELS = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
TOP_N_SERIES = 300

HOLDING_COST = 1.0
STOCKOUT_COST = 4.0
CRITICAL_RATIO = STOCKOUT_COST / (STOCKOUT_COST + HOLDING_COST)

SMOKE_N_SERIES = 6
SMOKE_LENGTH = 40
SMOKE_SEASONALITY = 4
SMOKE_HORIZON = 4
